### ISSUE TITLE
Function specification brainstorming （From William）

### ISSUE THREAD

**Issue by Tammy1128** [UBC-MDS/stock_analyzer#1]
- Data visualization
- Log-transformation 
- Moving average, some summary statistics
- Exponential smoothing
- Prediction (if time permits)

**Comment by Tammy1128** [comment]
Hey, we could also write a function to generate a correlation between features! (From William)

**Comment by Tammy1128** [comment]
To start, I think we could have a function that plot the stock, a function to plot the correlation heatmap, and a function to summarize some key statistics (avg price over 50 days, 1 month, 1 year, percentage change, etc.) (From William)

**Comment by ZIBOWANGKANGYU** [comment]
Regarding log-transformation, I believe it can be a parameter for Moving average, exponential smoothing and prediction. This way, users can choose whether to do modeling and prediction on raw data or logged data. We can also add ARIMA as another function. (see here https://towardsdatascience.com/the-complete-guide-to-time-series-analysis-and-forecasting-70d476bfe775)
